#!/usr/bin/env bash
# 打包「脱离源码仓库可运行」的 yFeiEye runtime 树（供 Ubuntu deb / Windows / macOS 安装包复用）
#
# 用法（在仓库根或任意目录）:
#   source COMPILE/lib/pack_desktop_runtime.sh
#   pack_source_free_runtime /path/to/runtime [VERSION] [ARCH]
#
# 环境变量:
#   REPO_ROOT   仓库根（默认从此脚本上溯两级再上一级）
set -euo pipefail

_pack_runtime_repo_root() {
  if [ -n "${REPO_ROOT:-}" ]; then
    echo "$REPO_ROOT"
    return
  fi
  local here
  here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  echo "$(cd "${here}/../.." && pwd)"
}

# pack_source_free_runtime <RUNTIME_ROOT> [VERSION] [ARCH]
pack_source_free_runtime() {
  local RUNTIME_ROOT="${1:?runtime root required}"
  local VERSION="${2:-latest}"
  local ARCH="${3:-}"
  local ROOT
  ROOT="$(_pack_runtime_repo_root)"

  if [ -z "$ARCH" ]; then
    case "$(uname -m 2>/dev/null || echo amd64)" in
      aarch64|arm64) ARCH=arm64 ;;
      x86_64|amd64|i686|i386) ARCH=amd64 ;;
      *) ARCH=amd64 ;;
    esac
  fi

  mkdir -p "$RUNTIME_ROOT"

  runtime_copy_file() {
    local rel="$1"
    local src="${ROOT}/${rel}"
    local dst="${RUNTIME_ROOT}/${rel}"
    [ -e "$src" ] || return 0
    mkdir -p "$(dirname "$dst")"
    if [ -d "$src" ]; then
      mkdir -p "$dst"
      # 不保留属主，避免非 root 打包失败
      cp -a --no-preserve=ownership "$src"/. "$dst"/ 2>/dev/null \
        || cp -R "$src"/. "$dst"/
    else
      cp -a --no-preserve=ownership "$src" "$dst" 2>/dev/null \
        || cp -f "$src" "$dst"
    fi
  }

  runtime_copy_glob() {
    local module="$1"
    local pattern="$2"
    local f rel
    shopt -s nullglob
    for f in "${ROOT}/${module}"/$pattern; do
      rel="${f#${ROOT}/}"
      runtime_copy_file "$rel"
    done
    shopt -u nullglob
  }

  runtime_copy_file "LICENSE"
  runtime_copy_file "README.md"
  runtime_copy_file "README_zh.md"
  printf 'V%s\n' "$VERSION" > "${RUNTIME_ROOT}/VERSION"

  # .scripts（保留部署脚本，排除运行数据、日志、venv）
  # --no-same-owner：非 root 解包时避免 chown 失败
  # 以下大目录桌面端不需要：
  #   docker-compose/ — 仅 Linux 离线 compose 二进制；脚本侧已容忍缺失（docker_compose_bundled.sh）
  #   go-view/ / nexus3/ / minio/ — 体积大或非桌面部署路径
  tar -C "${ROOT}" -cf - \
    --exclude='.scripts/docker/*_data' \
    --exclude='.scripts/docker/*_data/**' \
    --exclude='.scripts/docker/**/*_data' \
    --exclude='.scripts/docker/**/*_data/**' \
    --exclude='.scripts/docker/**/run' \
    --exclude='.scripts/docker/**/run/**' \
    --exclude='.scripts/docker/logs' \
    --exclude='.scripts/docker/logs/**' \
    --exclude='.scripts/docker/**/logs' \
    --exclude='.scripts/docker/**/logs/**' \
    --exclude='.scripts/docker/**/data' \
    --exclude='.scripts/docker/**/data/**' \
    --exclude='.scripts/docker/standalone-logs' \
    --exclude='.scripts/docker/standalone-logs/**' \
    --exclude='.scripts/postgresql/backup' \
    --exclude='.scripts/postgresql/backup/**' \
    --exclude='.scripts/zlmediakit/www/snap' \
    --exclude='.scripts/zlmediakit/www/snap/**' \
    --exclude='.scripts/zlmediakit/log' \
    --exclude='.scripts/zlmediakit/log/**' \
    --exclude='.scripts/mqtt-demo/run' \
    --exclude='.scripts/mqtt-demo/run/**' \
    --exclude='.scripts/industrial-demo/run' \
    --exclude='.scripts/industrial-demo/run/**' \
    --exclude='.scripts/**/__pycache__' \
    --exclude='.scripts/**/__pycache__/**' \
    --exclude='.scripts/**/.venv' \
    --exclude='.scripts/**/.venv/**' \
    --exclude='.scripts/**/venv' \
    --exclude='.scripts/**/venv/**' \
    --exclude='.scripts/**/node_modules' \
    --exclude='.scripts/**/node_modules/**' \
    --exclude='.scripts/**/.git' \
    --exclude='.scripts/**/.git/**' \
    --exclude='.scripts/minio' \
    --exclude='.scripts/minio/**' \
    --exclude='.scripts/docker-compose' \
    --exclude='.scripts/docker-compose/**' \
    --exclude='.scripts/go-view' \
    --exclude='.scripts/go-view/**' \
    --exclude='.scripts/nexus3' \
    --exclude='.scripts/nexus3/**' \
    .scripts | tar -C "${RUNTIME_ROOT}" --no-same-owner -xf - || true

  # 业务模块：仅部署相关文件（不带源码）
  local module
  for module in DEVICE AI VIDEO WEB APP VISUALIZE TRANSFORM NODE PANEL; do
    runtime_copy_glob "$module" "install_linux*.sh"
    runtime_copy_glob "$module" "install_mac.sh"
    runtime_copy_glob "$module" "install.sh"
    runtime_copy_glob "$module" "docker-compose*.yml"
    runtime_copy_glob "$module" "docker-compose*.yaml"
    runtime_copy_glob "$module" ".env"
    runtime_copy_glob "$module" ".env.*"
    runtime_copy_glob "$module" "env.example"
    runtime_copy_glob "$module" "panel.env.example"
    runtime_copy_glob "$module" "Dockerfile"
    runtime_copy_glob "$module" "Dockerfile.*"
    runtime_copy_glob "$module" "requirements*.txt"
    # AI/VIDEO 无源码运行时必需：去掉 ./:/app 挂载的 override
    runtime_copy_glob "$module" "docker-compose.source-free.yaml"
    if [ -d "${ROOT}/${module}/conf" ]; then
      runtime_copy_file "${module}/conf"
    fi
  done

  mkdir -p "${RUNTIME_ROOT}/.scripts/docker"
  cat > "${RUNTIME_ROOT}/.scripts/docker/.runtime_images_pulled" <<EOF
# Generated by COMPILE pack_source_free_runtime (desktop / source-free)
PULL_TIME=$(date '+%Y-%m-%d %H:%M:%S')
PULL_ARCH=${ARCH}
PULL_PROFILE=full
PULL_TAG=latest
SOURCE_FREE=1
EOF
  : > "${RUNTIME_ROOT}/.scripts/docker/.source_free_runtime"
  echo "full" > "${RUNTIME_ROOT}/.scripts/docker/.deploy_profile"
}
