package com.basiclab.iot.sink.javascript;

/**
 * 产品协议脚本内置模板（前端「应用模板」与文档共用）。
 */
public final class ProductScriptTemplates {

    private ProductScriptTemplates() {
    }

    /**
     * 默认骨架：仅包含上行解码 / 下行编码两个入口，供用户填写私有协议逻辑。
     */
    public static final String SKELETON = ""
            + "/**\n"
            + " * 产品私有协议编解码脚本\n"
            + " *\n"
            + " * rawDataToProtocol(topic, bytes)\n"
            + " *   上行解码：设备原始字节 → 平台标准 JSON（返回 byte[]）\n"
            + " *\n"
            + " * protocolToRawData(topic, message)\n"
            + " *   下行编码：平台标准消息 → 设备原始字节（返回 byte[] 或 UTF-8 字符串）\n"
            + " *\n"
            + " * 平台标准消息字段：tenantId, requestId, method, params, data, code, msg\n"
            + " * 常用辅助：jsUtil.toStandardMessage / toJsonString / utf8Bytes / bytesToUtf8\n"
            + " * 非本协议可 return bytes 透传，兼容设备已发标准 JSON 的场景\n"
            + " */\n"
            + "\n"
            + "/** 上行：设备 → 平台 */\n"
            + "function rawDataToProtocol(topic, bytes) {\n"
            + "  // TODO: 解析设备上行原始数据\n"
            + "  // var text = jsUtil.bytesToUtf8(bytes);\n"
            + "  // var params = jsUtil.newMap();\n"
            + "  // params.put('key', 'value');\n"
            + "  // return jsUtil.toStandardMessage(1, 'req001', 'thing.property.post', params);\n"
            + "  return bytes;\n"
            + "}\n"
            + "\n"
            + "/** 下行：平台 → 设备 */\n"
            + "function protocolToRawData(topic, message) {\n"
            + "  // TODO: 将平台下行消息编码为设备协议\n"
            + "  // var params = message.params || message.get('params');\n"
            + "  // var payload = jsUtil.toJsonString(params);\n"
            + "  // return jsUtil.utf8Bytes(payload);\n"
            + "  return jsUtil.utf8Bytes(jsUtil.toJsonString(message));\n"
            + "}\n";

    /**
     * 透传：设备已发标准 JSON，脚本不做变换（一般无需启用）。
     */
    public static final String PASSTHROUGH = ""
            + "/**\n"
            + " * 透传模板：设备已使用平台标准 JSON，脚本原样返回。\n"
            + " * 标准 JSON 可不配置脚本；本模板仅用于验证热加载链路。\n"
            + " */\n"
            + "function rawDataToProtocol(topic, bytes) {\n"
            + "  return bytes;\n"
            + "}\n"
            + "\n"
            + "function protocolToRawData(topic, message) {\n"
            + "  return jsUtil.utf8Bytes(jsUtil.toJsonString(message));\n"
            + "}\n";

    /**
     * 紧凑文本私有协议 EA|…（mqtt-demo 04/05 默认演示）。
     */
    public static final String COMPACT_TEXT = ""
            + "/**\n"
            + " * 紧凑文本私有协议（EasyAIoT EA 协议）\n"
            + " *\n"
            + " * 上行设备 → 平台（rawDataToProtocol）:\n"
            + " *   EA|UP|<tenantId>|<requestId>|<TYPE>|<k=v;k=v>\n"
            + " *   TYPE: PROP | EVENT | LOG | SVC_ACK | DESIRED_ACK\n"
            + " *\n"
            + " * 下行平台 → 设备（protocolToRawData）:\n"
            + " *   EA|DN|<requestId>|<TYPE>|<identifier>|<payload>\n"
            + " *   TYPE: SVC | SET\n"
            + " *\n"
            + " * 脚本将私有文本 ↔ 平台标准 JSON（tenantId/requestId/method/params）。\n"
            + " */\n"
            + "function rawDataToProtocol(topic, bytes) {\n"
            + "  var text = jsUtil.bytesToUtf8(bytes);\n"
            + "  if (text.indexOf('EA|UP|') !== 0) {\n"
            + "    // 非本协议则原样交给 Codec（兼容标准 JSON）\n"
            + "    return bytes;\n"
            + "  }\n"
            + "  var parts = text.split('|');\n"
            + "  // EA UP tenantId requestId TYPE kv\n"
            + "  if (parts.length < 6) {\n"
            + "    throw 'EA uplink format error: ' + text;\n"
            + "  }\n"
            + "  var tenantId = parseInt(parts[2], 10);\n"
            + "  var requestId = parts[3];\n"
            + "  var type = parts[4];\n"
            + "  var kv = parts.slice(5).join('|');\n"
            + "  var params = parseKv(kv);\n"
            + "  var method = 'thing.property.post';\n"
            + "  var code = null;\n"
            + "  var msg = null;\n"
            + "  var data = null;\n"
            + "  if (type === 'PROP') {\n"
            + "    method = 'thing.property.post';\n"
            + "  } else if (type === 'EVENT') {\n"
            + "    method = 'thing.event.post';\n"
            + "  } else if (type === 'LOG') {\n"
            + "    method = 'thing.log.post';\n"
            + "  } else if (type === 'SVC_ACK') {\n"
            + "    method = 'thing.service.invoke';\n"
            + "    data = { success: true };\n"
            + "    code = 0;\n"
            + "    msg = mapGet(params, 'msg') || 'ok';\n"
            + "  } else if (type === 'DESIRED_ACK') {\n"
            + "    method = 'thing.property.set';\n"
            + "    data = { success: true };\n"
            + "    code = 0;\n"
            + "    msg = mapGet(params, 'msg') || 'ok';\n"
            + "  }\n"
            + "  return jsUtil.toStandardMessage(tenantId, requestId, method, params, data, code, msg);\n"
            + "}\n"
            + "\n"
            + "function protocolToRawData(topic, message) {\n"
            + "  var method = String(mapGet(message, 'method') || '');\n"
            + "  var requestId = String(mapGet(message, 'requestId') || '');\n"
            + "  var params = mapGet(message, 'params') || {};\n"
            + "  var identifier = extractIdentifier(topic, method);\n"
            + "  var type = 'SVC';\n"
            + "  if (method.indexOf('property.set') >= 0 || (topic && topic.indexOf('/desired/set') >= 0)) {\n"
            + "    type = 'SET';\n"
            + "  } else {\n"
            + "    type = 'SVC';\n"
            + "  }\n"
            + "  // 禁止 JSON.stringify(Java Map)，会得到 {}\n"
            + "  var payload = typeof params === 'string' ? params : jsUtil.toJsonString(params);\n"
            + "  var line = 'EA|DN|' + requestId + '|' + type + '|' + identifier + '|' + payload;\n"
            + "  return jsUtil.utf8Bytes(line);\n"
            + "}\n"
            + "\n"
            + "function parseKv(text) {\n"
            + "  var map = jsUtil.newMap();\n"
            + "  if (!text) return map;\n"
            + "  var pairs = String(text).split(';');\n"
            + "  for (var i = 0; i < pairs.length; i++) {\n"
            + "    var p = pairs[i];\n"
            + "    if (!p) continue;\n"
            + "    var idx = p.indexOf('=');\n"
            + "    if (idx <= 0) continue;\n"
            + "    map.put(p.substring(0, idx), p.substring(idx + 1));\n"
            + "  }\n"
            + "  return map;\n"
            + "}\n"
            + "\n"
            + "function mapGet(obj, key) {\n"
            + "  if (obj == null) return null;\n"
            + "  if (typeof obj.get === 'function') {\n"
            + "    try { return obj.get(key); } catch (e) {}\n"
            + "  }\n"
            + "  return obj[key];\n"
            + "}\n"
            + "\n"
            + "function extractIdentifier(topic, method) {\n"
            + "  if (topic) {\n"
            + "    var segs = String(topic).split('/');\n"
            + "    // .../service/downstream/invoke/{id}\n"
            + "    for (var i = 0; i < segs.length; i++) {\n"
            + "      if (segs[i] === 'invoke' && i + 1 < segs.length) {\n"
            + "        return segs[i + 1];\n"
            + "      }\n"
            + "    }\n"
            + "    if (String(topic).indexOf('/desired/set') >= 0) {\n"
            + "      return 'desired';\n"
            + "    }\n"
            + "  }\n"
            + "  return method || 'unknown';\n"
            + "}\n";

    /**
     * 二进制私有协议（ReadBuffer / WriteBuffer）。
     */
    public static final String BINARY = ""
            + "/**\n"
            + " * 二进制私有协议\n"
            + " * 上行帧: magic(0xEA01) | type(u8) | tenantId(u32BE) | reqLen(u8)+reqId | kv...\n"
            + " * type: 1=PROP 2=SVC_ACK 3=DESIRED_ACK\n"
            + " * 下行帧: magic(0xEA02) | type(u8) | reqLen+reqId | idLen+id | payloadLen(u16BE)+payload\n"
            + " * type: 0x10=SVC 0x11=SET\n"
            + " */\n"
            + "function rawDataToProtocol(topic, bytes) {\n"
            + "  if (!bytes || bytes.length < 4) return bytes;\n"
            + "  var rb = jsUtil.readBuffer(bytes);\n"
            + "  var m1 = rb.readUB1();\n"
            + "  var m2 = rb.readUB1();\n"
            + "  if (m1 !== 0xEA || m2 !== 0x01) {\n"
            + "    return bytes;\n"
            + "  }\n"
            + "  var type = rb.readUB1();\n"
            + "  var tenantId = rb.readUB4();\n"
            + "  var reqLen = rb.readUB1();\n"
            + "  var requestId = rb.readString(reqLen);\n"
            + "  var params = jsUtil.newMap();\n"
            + "  var count = rb.readUB1();\n"
            + "  for (var i = 0; i < count; i++) {\n"
            + "    var kLen = rb.readUB1();\n"
            + "    var key = rb.readString(kLen);\n"
            + "    var vLen = rb.readUB2();\n"
            + "    var val = rb.readString(vLen);\n"
            + "    params.put(key, val);\n"
            + "  }\n"
            + "  var method = 'thing.property.post';\n"
            + "  var data = null; var code = null; var msg = null;\n"
            + "  if (type === 2) {\n"
            + "    method = 'thing.service.invoke'; data = { success: true }; code = 0; msg = 'ok';\n"
            + "  } else if (type === 3) {\n"
            + "    method = 'thing.property.set'; data = { success: true }; code = 0; msg = 'ok';\n"
            + "  }\n"
            + "  return jsUtil.toStandardMessage(tenantId, requestId, method, params, data, code, msg);\n"
            + "}\n"
            + "\n"
            + "function mapGet(obj, key) {\n"
            + "  if (obj == null) return null;\n"
            + "  if (typeof obj.get === 'function') {\n"
            + "    try { return obj.get(key); } catch (e) {}\n"
            + "  }\n"
            + "  return obj[key];\n"
            + "}\n"
            + "\n"
            + "function protocolToRawData(topic, message) {\n"
            + "  var wb = jsUtil.writeBuffer();\n"
            + "  wb.writeByte(0xEA);\n"
            + "  wb.writeByte(0x02);\n"
            + "  var method = String(mapGet(message, 'method') || '');\n"
            + "  var type = 0x10;\n"
            + "  if (method.indexOf('property.set') >= 0 || (topic && String(topic).indexOf('/desired/set') >= 0)) {\n"
            + "    type = 0x11;\n"
            + "  }\n"
            + "  wb.writeByte(type);\n"
            + "  var requestId = String(mapGet(message, 'requestId') || '');\n"
            + "  var reqBytes = jsUtil.utf8Bytes(requestId);\n"
            + "  wb.writeByte(reqBytes.length);\n"
            + "  wb.writeBytes(reqBytes);\n"
            + "  var identifier = 'svc';\n"
            + "  if (topic) {\n"
            + "    var segs = String(topic).split('/');\n"
            + "    for (var i = 0; i < segs.length; i++) {\n"
            + "      if (segs[i] === 'invoke' && i + 1 < segs.length) { identifier = segs[i + 1]; break; }\n"
            + "    }\n"
            + "  }\n"
            + "  var idBytes = jsUtil.utf8Bytes(identifier);\n"
            + "  wb.writeByte(idBytes.length);\n"
            + "  wb.writeBytes(idBytes);\n"
            + "  var payload = jsUtil.toJsonString(mapGet(message, 'params') || jsUtil.newMap());\n"
            + "  var pBytes = jsUtil.utf8Bytes(payload);\n"
            + "  wb.writeShortBE(pBytes.length);\n"
            + "  wb.writeBytes(pBytes);\n"
            + "  return wb.toArray();\n"
            + "}\n";
}
