spring:
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://14.18.122.2:5432/iot-node20?autoReconnect=true&useUnicode=true&characterEncoding=utf8&stringtype=unspecified
          username: postgres
          password: iot45722414822
  redis:
    host: 14.18.122.2
    port: 6379
    database: 0
    password: basiclab@iot975248395
